import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.css";
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./redux/Provider";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import GlobalError from "./error";

const inter = Inter({ subsets: ["latin"] });;

export const metadata: Metadata = {
  title: "Manage Employee App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ReduxProvider>
            <div className="header p-2 mb-3">
              <span>Employee Manager</span>
            </div>
            {children}
          </ReduxProvider>
      </body>
    </html>
  );
}
