import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.css";
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Inter } from "next/font/google";
import   "./globals.css";

const inter = Inter({ subsets: ["latin"] });;

export const metadata: Metadata = {
  title: "Manage Employee App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="header p-2 mb-3">
        <span>Employee Manager</span>
      </div>
        {children}
        </body>
    </html>
  );
}
